services:
  keycloak-db:
    image: postgres:latest
    command: postgres -c "max_connections=200"
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  pi-bank-db:
    image: postgres:latest
    container_name: pi-bank-db
    environment:
      POSTGRES_DB: dirigible
      POSTGRES_USER: dirigible
      POSTGRES_PASSWORD: dirigible
    volumes:
      - pi_bank_db_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dirigible"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      jgroups.dns.query: keycloak
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEME: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: https://keycloak.proper-invest.tech
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
      KC_FEATURES: preview
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - shared_network

  pi-bank:
    image: ghcr.io/tivmof/pi-bank-backend:latest
    container_name: pi-bank-backend
    environment:
      DIRIGIBLE_MULTI_TENANT_MODE: false
      SPRING_PROFILES_ACTIVE: keycloak
      DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: https://keycloak.proper-invest.tech/realms/pi-bank
      DIRIGIBLE_KEYCLOAK_CLIENT_ID: pi-bank-backend
      DIRIGIBLE_KEYCLOAK_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET}
      DIRIGIBLE_TRIAL_ENABLED: true
      DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES: PostgreSQL
      PostgreSQL_DRIVER: org.postgresql.Driver
      PostgreSQL_URL: jdbc:postgresql://pi-bank-db:5432/dirigible
      PostgreSQL_USERNAME: dirigible
      PostgreSQL_PASSWORD: dirigible
      DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT: PostgreSQL
    depends_on:
      - keycloak
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/tivmof/pi-online-bank/deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot:ro
      - /home/tivmof/nginx/nginx-certs/live/proper-invest.tech:/etc/nginx/certs/live/proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/live/keycloak.proper-invest.tech:/etc/nginx/certs/live/keycloak.proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/archive/proper-invest.tech:/etc/nginx/certs/archive/proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/archive/keycloak.proper-invest.tech:/etc/nginx/certs/archive/keycloak.proper-invest.tech:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - pi-bank
      - keycloak
    networks:
      - shared_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/tivmof/nginx/nginx-certs:/etc/letsencrypt
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot
    networks:
      - shared_network

volumes:
  keycloak_db_data:
    driver: local
  pi_bank_db_data:
    driver: local

networks:
  shared_network:
    driver: bridge
