# version: '3.9'

# services:

#   backend:
#     image: ghcr.io/tivmof/pi-bank-backend:latest
#     container_name: backend
#     ports:
#       - "80:80"
#     environment:
#       spring.profiles.active: keycloak
#       DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: https://auth.eu1.codbex.com/auth/realms/demo
#       DIRIGIBLE_KEYCLOAK_CLIENT_ID: pi-online-bank
#       DIRIGIBLE_MULTI_TENANT_MODE: "false"
#       DIRIGIBLE_TRIAL_ENABLED: "true"


version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "90:8080"

  backend:
    image: ghcr.io/tivmof/pi-bank-backend:latest
    container_name: pi-bank-backend
    ports:
      - "80:80"
    environment:
      spring.profiles.active: keycloak
      DIRIGIBLE_KEYCLOAK_ENABLED: true
      DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: http://localhost:90/realms/pi-bank
      DIRIGIBLE_KEYCLOAK_CLIENT_ID: pi-bank-backend
      DIRIGIBLE_KEYCLOAK_CLIENT_SECRET: L4N8g8NjdGxnudhpMVK7Ii6fX5nciFk4
      DIRIGIBLE_MULTI_TENANT_MODE: "false"
      DIRIGIBLE_TRIAL_ENABLED: "true"
    depends_on:
      - keycloak