services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - shared_network

  backend:
    image: ghcr.io/tivmof/pi-bank-backend:latest
    container_name: pi-bank-backend
    environment:
      spring.profiles.active: keycloak
      DIRIGIBLE_KEYCLOAK_ENABLED: true
      DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/realms/pi-bank
      DIRIGIBLE_KEYCLOAK_CLIENT_ID: pi-bank-backend
      DIRIGIBLE_MULTI_TENANT_MODE: "false"
      DIRIGIBLE_TRIAL_ENABLED: "true"
    depends_on:
      - keycloak
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/tivmof/pi-online-bank/deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot:ro
      - /home/tivmof/nginx/nginx-certs/live/proper-invest.tech:/etc/nginx/certs/live/proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/archive/proper-invest.tech:/etc/nginx/certs/archive/proper-invest.tech:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - keycloak
    networks:
      - shared_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/tivmof/nginx/nginx-certs:/etc/letsencrypt
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
