services:
  postgres:
    image: postgres:latest
    command: postgres -c "max_connections=200"
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start --hostname=keycloak.proper-invest.tech
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEME: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak.proper-invest.tech
      KC_HOSTNAME_URL: https://keycloak.proper-invest.tech
      KC_HOSTNAME_ADMIN_URL: https://keycloak.proper-invest.tech
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network

  pi-bank:
    image: ghcr.io/tivmof/pi-bank-backend:latest
    container_name: pi-bank-backend
    environment:
      spring.profiles.active: keycloak
      DIRIGIBLE_KEYCLOAK_ENABLED: true
      DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: https://keycloak.proper-invest.tech/realms/pi-bank
      DIRIGIBLE_KEYCLOAK_CLIENT_ID: pi-bank-backend
      DIRIGIBLE_MULTI_TENANT_MODE: "false"
      DIRIGIBLE_TRIAL_ENABLED: "true"
    depends_on:
      - keycloak
    volumes:
      - pi_bank_data:/target 
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/tivmof/pi-online-bank/deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot:ro
      - /home/tivmof/nginx/nginx-certs/live/proper-invest.tech:/etc/nginx/certs/live/proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/live/keycloak.proper-invest.tech:/etc/nginx/certs/live/keycloak.proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/archive/proper-invest.tech:/etc/nginx/certs/archive/proper-invest.tech:ro
      - /home/tivmof/nginx/nginx-certs/archive/keycloak.proper-invest.tech:/etc/nginx/certs/archive/keycloak.proper-invest.tech:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - pi-bank
      - keycloak
    networks:
      - shared_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/tivmof/nginx/nginx-certs:/etc/letsencrypt
      - /home/tivmof/nginx/nginx-challenges:/var/www/certbot
    networks:
      - shared_network

volumes:
  keycloak_data:
    driver: local
  pi_bank_data:
    driver: local
  postgres_data:
    driver: local

networks:
  shared_network:
    driver: bridge
