name: Deploy - PI Bank Backend

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy Backend and Keycloak
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            # Pull the latest backend image
            docker pull ghcr.io/tivmof/pi-bank-backend:${{ github.event.release.tag_name }}
            
            # Stop and remove any existing containers
            docker-compose -f /path/to/docker-compose.yml down || true
            
            # Update docker-compose.yml with the new tag
            sed -i "s|ghcr.io/tivmof/pi-bank-backend:.*|ghcr.io/tivmof/pi-bank-backend:${{ github.event.release.tag_name }}|" /path/to/docker-compose.yml
            
            # Start the backend and Keycloak
            docker-compose -f /path/to/docker-compose.yml up -d
