name: Release - PI Bank Backend

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install TypeScript compiler
        run: npm i -g typescript
  
      - name: TypeScript Build
        run: |
          cd pi-bank-backend
          tsc --pretty > tsc-output.log 2>&1 || true

          grep -v 'TS2688' tsc-output.log > filtered-tsc-output.log

          cat filtered-tsc-output.log

          if grep -q 'error TS' filtered-tsc-output.log; then
              exit 1
          fi

      - name: Install Dependencies
        run: |
          cd ./pi-bank-backend
          echo "@codbex:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.DOCKER_PASSWORD }}" > .npmrc
          npm install
          rm -rf .npmrc

      - name: "Configure Git"
        run: |
          git fetch
          git checkout main  # Checkout the branch you want to release from
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Initialize Buildx
        run: |
          docker buildx create --name builder || true
          docker buildx use builder

      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker buildx build --tag pi-bank-backend -o type=image --platform=linux/arm64,linux/amd64 .
          docker buildx build --push --tag ghcr.io/tivmof/pi-bank-backend:${{ inputs.release-version }} -o type=image --platform=linux/arm64,linux/amd64 .

      - name: Create and Push Release Branch
        run: |
          git checkout -b release/${{ inputs.release-version }}
          git push --set-upstream origin release/${{ inputs.release-version }}

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ inputs.release-version }}
          name: ${{ inputs.release-version }}
          draft: false
          prerelease: false
          files: |
            LICENSE
          body: |
            ## Release - ${{ inputs.release-version }}
